_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 71
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 71
                - 103
            "3":
                - 23
                - 55
            "4": 3.9.19
            "5": 0.19.1
            "6": 4.45.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
